# Generated by Django 5.1.4 on 2024-12-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivaraity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivaraity',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KL', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELACHI'), ('GN', 'GREEN'), ('WH', 'WHITE'), ('OG', 'OOLONG'), ('TI', 'TISANES'), ('RO', 'ROOIBOS'), ('MA', 'MATCHA'), ('PU', 'PU-ERH'), ('YE', 'YELLOW')], max_length=2),
        ),
    ]
