# Generated by Django 5.1.4 on 2024-12-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_chaicertificate_chairiview_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairiview',
            name='comment',
            field=models.TextField(),
        ),
    ]
