# Generated by Django 5.1.4 on 2024-12-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0007_chaivaraity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivaraity',
            name='price',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
