# Generated by Django 5.1.4 on 2024-12-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0008_alter_chaivaraity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivaraity',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
