# Generated by Django 5.1.4 on 2024-12-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0009_alter_chaivaraity_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('tea_name', models.CharField(max_length=100)),
                ('tea_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_tea', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
