# Generated by Django 5.1.4 on 2024-12-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0011_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
